create table faculty
(
    id    bigint not null primary key,
    color varchar(255),
    name  varchar(255)
);

create table student
(
    id         bigint  not null primary key,
    age        integer not null,
    faculty_id bigint constraint fk_student_to_faculty references faculty,
    name       varchar(255)
);

create table avatar
(
    id         bigint generated by default as identity primary key,
    file_size  bigint not null,
    student_id bigint unique constraint fk_avatar_to_student references public.student,
    file_path  varchar(255),
    media_type varchar(255),
    data       oid
);


